### ISSUE TITLE
Allow client apps to override the SHDBugReport class

### ISSUE THREAD

**Issue by jeanregisser** [maxgoedjen/Shakedown#12]
Hi,

In my app I want to have a custom formatting for the bug report text.
For now I've swizzled the `formattedReport` method of the `SHDBugReport` with my own custom method.
It would be much nicer if we could set the `SHDBugReport` subclass we'd like to use.

Here's how I see it:

``` objc
// Use a custom bug report class
[SHDShakedown sharedShakedown].bugReportClass = [MyCustomBugReport class];
```

Also `setBugReportClass` would check if the given class is a subclass of `SHDBugReport` to ensure it's compatible with the rest of the code.

What do you think?
This is quite trivial, I can send a pull request with these changes if you agree with it.

**Comment by maxgoedjen** [comment]
Yep, I'm game. Wire it up.
